# Generated by Django 3.2.6 on 2021-12-27 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_feedback_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='author',
            new_name='author_id',
        ),
    ]
