# Generated by Django 3.2.6 on 2021-12-27 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20211227_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback_text',
            new_name='text',
        ),
    ]
